#!/bin/sh
#
# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

#make sure we want to commit to the release branch if that's where we are.
checkRelease (){
	BRANCH="$(git symbolic-ref HEAD 2>/dev/null)" || BRANCH="(unnamed branch)"
	BRANCH=${BRANCH##refs/heads/}
	if [ $BRANCH = 'release' ]; then
		while true; do
			echo -ne '\033[38;5;57mAre you sure you wish to commit to the release branch? [y,n]\033[39m'; read
			case $REPLY in
			[Yy])
				exit 0
				;;
			[NnQq])
				echo -e '\033[38;5;49mGit Commit aborted.\033[39m'
				exit 1
				;;
			esac
		done
	fi
}

# Call our hook functions
checkRelease
