#!/bin/bash
#
# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

#make sure we want to commit to the release branch if that's where we are.
checkRelease (){
	TMPBRANCH="$(git symbolic-ref HEAD 2>/dev/null)" || TMPBRANCH="(unnamed branch)"
	BRANCH=${TMPBRANCH##refs/heads/}
	if [ $BRANCH = 'master' -o $BRANCH = 'production' -o $BRANCH = 'release' -o $BRANCH = 'development' ]; then
		while true; do
			echo -ne "\033[38;5;57mAre you sure you wish to commit to the \033[38;5;49m$BRANCH\033[39m\033[38;5;57m branch? [y,n]\033[39m"; read
			case $REPLY in
			[Yy])
				exit 0
				;;
			[NnQq])
				echo -e '\033[31;5;49mCommit aborted.\033[39m'
				exit 1
				;;
			esac
		done
	fi
}

# Call our hook functions
checkRelease
