#!/usr/bin/env python
""" Git hook for pylint checks """
# pylint: disable=invalid-name

import sys


try:
    from git_pylint_commit_hook.commit_hook import check_repo
    MIN_QUALITY = 10
    if not check_repo(limit=MIN_QUALITY, suppress_report=True):
        print("\033[31;5;49mPylint tests failing. Commit aborted.\033[39m")
        sys.exit(1)
    else:
        sys.exit(0)
except ImportError:
    print('\033[1;33;49mPylint import failed. Not installed in python path. Ignoring and continuing.\033[39m')
    sys.exit(0)
