[tool.black]
line-length = 80
safe = true
target-version = ['py37']
exclude = '/(\.git|owlet|protos)/'

[tool.isort]
force_single_line = true
include_trailing_comma = true
known_powlet = 'powlet'
line_length = 80
lines_after_imports = 2
multi_line_output = 3  # Vertical Hanging Indent
remove_imports = [ 'from app.models.set import Set' ]
sections = [
    'FUTURE',
    'STDLIB',
    'THIRDPARTY',
    'POWLET',
    'FIRSTPARTY',
    'LOCALFOLDER',
]
skip = 'owlet, protos'

[tool.pylint.master]
extension-pkg-allow-list = "dependency_injector"
jobs = 4
persistent = "no"

[tool.pylint.format]
good-names = [ "T","d","db","df","e","i","id","logger","ns","tz" ]
ignore-long-lines='''
(?x)(
  ^\s*(\#\ )?<?https?://\S+>?$|
  ^\s*(from\s+\S+\s+)?import\s+.+$|
  ^\s*"\S+"$)
'''
max-line-length = 80
single-line-if-stmt = "yes"

[tool.pylint.similarities]
ignore-imports = "yes"

[tool.pylint.global.messages_control]
disable = [
    "fixme",  # We intentionally leave TODOs in the code.
    "missing-module-docstring",  # We don't require them.
    # Disabled so that my editor reminds me to deal with it
    # "ungrouped-imports",  # Leave it to isort.
    # "wrong-import-order",  # Leave it to isort.
    # "wrong-import-position",  # Leave it to isort.
]
