[tool.black]
line-length = 88
target-version = ['py310']
exclude = '/(\.git)/'

[tool.isort]
force_single_line = true
include_trailing_comma = true
line_length = 88
lines_after_imports = 2
multi_line_output = 3  # Vertical Hanging Indent
sections = [
    'FUTURE',
    'STDLIB',
    'THIRDPARTY',
    'FIRSTPARTY',
    'LOCALFOLDER',
]
use_parentheses = true

[tool.pylint.master]
extension-pkg-allow-list = "dependency_injector"
fail-on = "I"  # Fail on informational (e.g. useless-suppression).
jobs = 4
persistent = "no"
init-hook='import sys; sys.path.append(".")'
ignore-paths = ["alembic/versions"]

[tool.pylint.typecheck]
ignored-classes = [
    # SQLAlchemy false positives
    "sqlalchemy.orm.scoping.scoped_session",
    "sqlalchemy.orm.session.sessionmaker"
]

[tool.pylint.format]
good-names = [ "T", "d", "db", "df", "e", "i", "id", "logger", "ns", "tz" ]
ignore-long-lines='''
(?x)(
  ^\s*(\#\ )?<?https?://\S+>?$|
  ^\s*(from\s+\S+\s+)?import\s+.+$|
  ^\s*"\S+"$)
'''
# Note this is intentionally different than the black and isort settings. We want a "soft"
# limit of 100. Let black be in charge of managing line length until it gets out of hand
# an pylint needs to complain.
max-line-length = 100
single-line-if-stmt = "yes"

[tool.pylint.similarities]
ignore-imports = "yes"

[tool.pylint.messages_control]
enable = [
   "useless-suppression",
]
disable = [
    "duplicate-code", # Tends to be false positives in test code
    "fixme",  # We intentionally leave TODOs in the code.
    "missing-module-docstring",  # We don't require them.
    "too-few-public-methods", # Small classes are fine
    "ungrouped-imports",  # Leave it to isort.
    "wrong-import-order",  # Leave it to isort.
    "wrong-import-position",  # Leave it to isort.
]

[tool.bandit]
exclude_dirs = ["tests"]
