#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.

pip install bpython pylint flake8 black isort pytest coverage bandit poetry pytest-only mypy pdbpp
pip install -r requirements-dev.txt  || pip install -r requirements.txt || poetry install
